### ISSUE TITLE
Add a finer runtime export

### ISSUE THREAD

**Issue by jjerphan** [conda-forge/curl-feedstock#143]
Currently there's [a runtime requirement on `libcurl`](https://github.com/conda-forge/curl-feedstock/blob/main/recipe/meta.yaml#L50-L51), but it is unconstrained.

It probably needs to be pinned on a major or a minor version.

See: https://abi-laboratory.pro/?view=timeline&l=curl

**Comment by xylar** [comment]
It looks to me like major version would be sufficient. Since that hasn't changed in about 20 years, the current situation doesn't seem all that risky.

**Comment by xylar** [comment]
Ah, sorry. It did change more recently to 8. So ignore what I said. Seems like abilab is about 4 years behind.

**Comment by isuruf** [comment]
> Currently there's [a runtime requirement on libcurl](https://github.com/conda-forge/curl-feedstock/blob/main/recipe/meta.yaml#L50-L51), but it is unconstrained.

This is untrue. You can extract the libcurl package and check the contents of `run_exports.json` to verify that it is not unconstrained.

`pin_subpackage("libcurl")` is equivalent to `pin_subpackage("libcurl", max_pin="x", min_pin="x.x.x.x.x.x")`

**Comment by isuruf** [comment]
If the major is not enough, then we probably need to have `max_pin="x.x"`, but there's not enough evidence that this is needed.

**Comment by jjerphan** [comment]
> This is untrue. You can extract the libcurl package and check the contents of `run_exports.json` to verify that it is not unconstrained.

This is what I wanted to say. To me, `pin_subpackage("libcurl", max_pin="x", min_pin="x.x.x.x.x.x")` does not set constraints when Semantic Versioning is used.

**Comment by jjerphan** [comment]
> there's not enough evidence that this is needed.

I opened a PR to keep track of the problem which was observed in https://github.com/conda-forge/mamba-feedstock/pull/246. I will spend more time writing a comprehensive description when I get some.

**Comment by jjerphan** [comment]
[The `libcurl` team takes care in having ABI stability](https://curl.se/libcurl/features.html), and we observed the absence of this problem with `libcurl` 8.10.1 (so the problem was likely a bug in 8.10.0 which was fixed in 8.10.1): hence runtime requirements aren't needed for `libcurl`; sorry for the disturbance.
