### ISSUE TITLE
libcurl can crash when called from non-main thread

### ISSUE THREAD

**Issue by kuepe-sl** [conda-forge/curl-feedstock#19]
libcurl uses SIGALRM by default for realizing timeouts. This causes crashes when certain functions are called from a non-main thread as described [here](https://www.redhat.com/archives/libvir-list/2012-September/msg01960.html).

This can be solved by configuring with --enable-threaded-resolver or --enable-ares.

**Comment by ocefpaf** [comment]
Closing this with #18
