### ISSUE TITLE
Update curl to >= 7.50 on win

### ISSUE THREAD

**Issue by nehaljwani** [conda-forge/curl-feedstock#22]
On Windows 7, the current version of curl 7.49, is buggy, and needs this fix: https://github.com/curl/curl/commit/34855fe , which was released in 7.50

**Comment by jakirkham** [comment]
Unfortunately don't have time to address it myself. Would happily review a PR though.

**Comment by nehaljwani** [comment]
The recipe right now is on 7.54.1, but for windows, it doesn't build correctly. I had sent a PR to fix this at https://github.com/conda-forge/curl-feedstock/pull/21 (hack to break the dependency cycle)

**Comment by nehaljwani** [comment]
This has been fixed by https://github.com/conda-forge/curl-feedstock/pull/21
