### ISSUE TITLE
undefined symbol: libssh2_scp_recv2

### ISSUE THREAD

**Issue by quartox** [conda-forge/curl-feedstock#23]
Error when trying to load libhdfs3 (https://github.com/conda-forge/hdfs3-feedstock/issues/4#issuecomment-335294853):

```
>>> ctypes.cdll.LoadLibrary('libhdfs3.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jlord/.conda/envs/dask/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/home/jlord/.conda/envs/dask/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/jlord/.conda/envs/dask/lib/python3.6/lib-dynload/../.././libcurl.so.4: undefined symbol: libssh2_scp_recv2
```

Downgrading from `7.54.1` to `7.49.1` resolves the issue for me.

**Comment by ocefpaf** [comment]
Seems related to https://github.com/curl/curl/issues/1035

I'm investigating what can be done to solve that.

**Comment by zhenyisong** [comment]
@quartox Thanks. I downgraded the curl lib ( conda install curl=7.49.1) and this problem is solved as your suggestion.

**Comment by smithsp** [comment]
Adding myself so that I get updated on progress, and remind myself to remove pinning of curl dependency in omfit recipe.

**Comment by jakirkham** [comment]
Is anyone here setting `LD_LIBRARY_PATH`? If so, please try unsetting `LD_LIBRARY_PATH` and retrying.

The `curl` build does link against `libssh2`, which we also build and package, and our copy of `libssh2` has the `libssh2_scp_recv2` symbol. So am not seeing anything actionable here. Also have no problem loading `libcurl.so.4.4.0`.

```python
>>> import ctypes
>>> ctypes.cdll.LoadLibrary('libcurl.so.4.4.0')
```

**Comment by jakirkham** [comment]
We now [test for this symbol on Linux]( https://github.com/conda-forge/curl-feedstock/blob/db7c6d133296b41a66bec17d4b89542fb4db2272/recipe/meta.yaml#L56 ) as well. So this issue has either been resolved with `curl` or something else is going on (e.g. old/broken `curl` package pulled in, etc.)

**Comment by jakirkham** [comment]
Think PR ( https://github.com/conda-forge/curl-feedstock/pull/29 ) should have resolved any potentially incorrect loading order.
