### ISSUE TITLE
/libcurl.so.4: undefined symbol: SSL_CTX_set_alpn_protos

### ISSUE THREAD

**Issue by roryk** [conda-forge/curl-feedstock#24]
On a couple CentOS, Ubuntu and on a few RHEL6/7 Vagrant boxes this works fine. But on an older RH box, it looks like the `curl` feedstock isn't linked correctly, which breaks some packages that depend on it. 

For example:

```
conda create -n rcurl-test
source activate rcurl-test
conda install -c conda-forge r-rcurl
(rcurl-test) -bash-4.1$ Rscript -e 'library(RCurl')
-bash: syntax error near unexpected token `)'
(rcurl-test) -bash-4.1$ Rscript -e 'library(RCurl)'
Loading required package: methods
Loading required package: bitops
Error: package or namespace load failed for âRCurlâ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/gpfs/users/kbdt501/local/share/bcbio/anaconda/envs/rcurl-test/lib/R/library/RCurl/libs/RCurl.so':
  /gpfs/users/kbdt501/local/share/bcbio/anaconda/envs/rcurl-test/lib/R/library/RCurl/libs/../../../../libcurl.so.4: undefined symbol: SSL_CTX_set_alpn_protos
Execution halted
```

```
Linux version 2.6.32-431.el6.x86_64 (mockbuild@x86-023.build.eng.bos.redhat.com) (gcc
 version 4.4.7 20120313 (Red Hat 4.4.7-4)  (GCC) ) #1 SMP Sun Nov 10 22:19:54 EST 2013
```

Installing `libcurl` from `defaults` fixes the issue, so if we could build this `curl` similar to that one it would fix the problem.

**Comment by roryk** [comment]
Downgrading to 7.49.1 as suggested in #23 fixes this issue as well.

**Comment by roryk** [comment]
I had some detritus in my LD_LIBRARY_PATH, which fixes this problem after I remove it.

**Comment by jakirkham** [comment]
Yeah setting `LD_LIBRARY_PATH` outside of a build is generally a recipe for trouble. Good to close?

**Comment by roryk** [comment]
Yep, sorry for the false alarm!

**Comment by nsoranzo** [comment]
I got bitten by this issue too, will be fixed by https://github.com/conda-forge/curl-feedstock/pull/29 .

**Comment by roryk** [comment]
Thanks for making an actual fix for this issue!
