### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by cpaulik** [conda-forge/curl-feedstock#46]
Could this be built against nghttp2? See https://curl.haxx.se/docs/http2.html 

This would then enable HTTP2 support in downstream libraries like e.g. gdal.

**Comment by ocefpaf** [comment]
I'm OK with that. Do you want to send a PR?

**Comment by cpaulik** [comment]
I'll try. But that does mean that we first need to make a nghttp2 feedstock?

**Comment by ocefpaf** [comment]
> I'll try. But that does mean that we first need to make a nghttp2 feedstock?

Yep. We need a `nghttp2` package first.

**Comment by jakirkham** [comment]
Raised an issue on `staged-recipes` to track the package request. ( https://github.com/conda-forge/staged-recipes/issues/8750 )

**Comment by cpaulik** [comment]
I started on a merge request for nghttp2 in https://github.com/conda-forge/staged-recipes/pull/8752

Still having problems with building it locally for testing.

```
./.circleci/run_docker_build.sh
```

and also the more direct 

```
docker run -it -v /home/cpa/workspace/conda-forge-feedstocks/staged-recipes:/home/conda/staged-recipes condaforge/linux-anvil-comp7 /bin/bash
```

Does nothing which seems strange.

**Comment by jakirkham** [comment]
Do you have Docker installed?

**Comment by cpaulik** [comment]
Yes. I can `docker run -it` other images without problems. Will investigate tomorrow and update the recipe after I've run some local tests. No idea what the output of nghttp2 should be otherwise.

**Comment by jakirkham** [comment]
Interesting. Yeah `./.circleci/run_docker_build.sh` should work.

Simplifying things a bit. Are you able to do this?

```
docker run --rm -it condaforge/linux-anvil-comp7
```

**Comment by cpaulik** [comment]
Doing a 

```
docker run -it condaforge/linux-anvil-comp7 
```

without the `--rm`

leaves me with the following:

```
docker ps -a
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                       PORTS                    NAMES
c0adeb6ea41d        condaforge/linux-anvil-comp7   "/opt/conda/bin/tini…"   3 seconds ago       Exited (139) 3 seconds ago                            relaxed_greider
```

So it seems there is something going very wrong. 

Should I open an issue in https://github.com/conda-forge/docker-images instead of spamming this thread.

**Comment by cpaulik** [comment]
Does one of you know why openssl is pinned to different versions in `curl` and `nghttp2`? See the failing build in https://github.com/conda-forge/curl-feedstock/pull/60
