### ISSUE TITLE
need to rebuild 7.64.1 with latest kbr5 pin

### ISSUE THREAD

**Issue by xylar** [conda-forge/curl-feedstock#68]
see https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/537

**Comment by xylar** [comment]
I'll do this tomorrow...

**Comment by isuruf** [comment]
Let's just bump the pinning to 7.68.0 in conda-forge/conda-forge-pinning-feedstock#537. There's absolutely no reason to rebuild 7.64.1

**Comment by xylar** [comment]
Sounds good. Or even wait for 7.69.1?

**Comment by CJ-Wright** [comment]
We might consider making a `7.68` branch if it is going to be supported long term. This way when the bot properly issues rebuild PRs into all branches on a feedstock this one will be ready.

**Comment by isuruf** [comment]
But there's absolutely no reason to support `7.68` long term.

**Comment by CJ-Wright** [comment]
Ok, that was more a generic statement about if we are supporting things long term (there are already two branches on this feedstock) then we might consider branches to be a good approach, since the bot can issue PRs into them.

**Comment by jakirkham** [comment]
The bot submits PRs to non-`master` branches?

**Comment by CJ-Wright** [comment]
Not yet but it is a feature we'd like to have in the future.

**Comment by ocefpaf** [comment]
I just rebuilt `7.64.1` but I agree with @isuruf, bumping the pin is better in the long run.
