### ISSUE TITLE
curl 7.71.1 _3 broken on osx

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/curl-feedstock#77]
If I install the _3 build:
```
>conda install --offline curl=7.71.1=hbdca1c0_3
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/rmay/miniconda3

  added / updated specs:
    - curl==7.71.1=hbdca1c0_3


The following packages will be UPDATED:

  curl                                    7.71.1-hbdca1c0_2 --> 7.71.1-hbdca1c0_3
  libcurl                                 7.71.1-he6690cf_2 --> 7.71.1-he6690cf_3


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
I get a completely broken curl on osx:
```
>curl
dyld: Library not loaded: @rpath/libssh2.1.dylib
  Referenced from: /Users/rmay/miniconda3/lib/libcurl.4.dylib
  Reason: image not found
[1]    20759 abort      curl
```

**Comment by ocefpaf** [comment]
xref.: https://github.com/conda-forge/admin-requests/pull/98

**Comment by dopplershift** [comment]
One of the more annoying parts of this is what happens to conda:
```
>conda update --all  
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/osx-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

'https://repo.anaconda.com/pkgs/main/osx-64'
```

Also @ocefpaf, should this really be closed?

**Comment by isuruf** [comment]
`_3` is not broken. It's just that upgrading from `_2` to `_3` will result in a broken environment. Can't do anything except tell users to do `conda install libssh2 --force-reinstall`

**Comment by dopplershift** [comment]
Except once `_3` is installed, conda is non-functional. This is in my *base* environment--this update bricks my entire conda install.

**Comment by isuruf** [comment]
Issue is that once `_2` is installed, you'll not be able to update the environment ever.

**Comment by dopplershift** [comment]
If I do:
```
conda install --offline --force-reinstall libssh2
```
it then complains about `libssl.1.1.dylib` missing.

**Comment by isuruf** [comment]
You need force reinstall `openssl` too

**Comment by dopplershift** [comment]
And `krb5` it turns out (`libgssapi_krb5.2.2.dylib`).

So for posterity, my full fix was essentially:
```
conda install --offline --force-reinstall libssh2 openssl krb5
```

**Comment by wolfv** [comment]
I am really sorry @dopplershift :/

**Comment by dopplershift** [comment]
No worries, I was more concerned about anyone else who ended up in that boat (e.g. users I might need to support on my end) but looks like I got the problematic `_2` over the weekend so probably not a lot of others who will hit this. Fixing a busted env is just another day that ends in "y" for me 😆
