### ISSUE TITLE
ClobberWarning: This transaction has incompatible packages due to a shared path

### ISSUE THREAD

**Issue by jschueller** [conda-forge/curl-feedstock#78]
I got a warning on windows, supposedly curl and libcurl have a conflict:
```
ClobberWarning: This transaction has incompatible packages due to a shared path.
2020-08-05T12:08:13.0883381Z   packages: conda-forge/win-64::libcurl-7.71.1-h4b64cdc_4, conda-forge/win-64::curl-7.71.1-h4b64cdc_4
2020-08-05T12:08:13.0884015Z   path: 'library/bin/curl.exe'
```
However the files section of libcurl seems correct and does not list the .exe

**Comment by hmaarrfk** [comment]
The file is there in the tar

![image](https://user-images.githubusercontent.com/90008/91661139-ecf5aa80-ea8e-11ea-9489-25fbf2f4869c.png)
