### ISSUE TITLE
tests with ssl cert

### ISSUE THREAD

**Issue by marqh** [conda-forge/curl-feedstock#8]
Hello

I'm trying to use this recipe and build it locally, as part of an investigation

I'm getting errors, I believe related to the configure options:
https://github.com/conda-forge/curl-feedstock/blob/master/recipe/build.sh#L13

in particular, the tests are looking for a CAfile in a location where it does not exist on my host
I have `/etc/ssl/cacert.pem` but not an `ssl/`cacert.pem` within the build or _test areas

I am not sure if I am missing something, but I hoped I could establish that I could build this recipe locally.  Clearly this has built and is available, so I should be able to rebuild it

all advice gratefully received

marqh

**Comment by jakirkham** [comment]
Could you please provide `conda list` for the relevant environment? Please make sure [`show_channel_urls`]( http://conda.pydata.org/docs/config.html#show-channel-urls-show-channel-urls ) is set to `true` in your `.condarc` before generating this list. Also `conda info` would be nice for good measure. Thanks.

**Comment by jakirkham** [comment]
FWIW normally there is a `ca-certificates` package that gets pulled in and has the certs. It provides these in `PREFIX/ssl` for historic reasons. So I'm basically trying to understand why that is not the case.

**Comment by marqh** [comment]
Hi @jakirkham 

I've looked into my build process and I have a customised openssl recipe which is building quite differently from the conda-forge one. 

I think there are things this recipe is expecting which I'm not providing.

So, I think this is my problem, not yours
I'm happy for you to close this issue if you agree

**Comment by jakirkham** [comment]
Possibly, that being said if you want to share more details, I would be more than happy to help.

**Comment by marqh** [comment]
> Possibly, that being said if you want to share more details, I would be more than happy to help.

thank you, but there's no need now
