### ISSUE TITLE
curl.exe removed form curl, not just libcurl

### ISSUE THREAD

**Issue by xylar** [conda-forge/curl-feedstock#82]
I downloaded and untarred the latest win build:
https://anaconda.org/conda-forge/curl/7.71.1/download/win-64/curl-7.71.1-h4b64cdc_6.tar.bz2
```
$ tar xvf curl-7.71.1-h4b64cdc_6.tar.bz2 
info/paths.json
info/hash_input.json
info/index.json
info/about.json
info/files
info/git
info/recipe/parent/build.sh
info/test/run_test.bat
info/recipe/parent/install_static.bat
info/recipe/parent/install_dll.bat
info/recipe/parent/bld.bat
info/licenses/COPYING
info/recipe/conda_build_config.yaml
info/recipe/meta.yaml
info/recipe/parent/meta.yaml
```
and there is no `Library/bin/curl.exe`

I did the same for the previous build:
https://anaconda.org/conda-forge/curl/7.71.1/download/win-64/curl-7.71.1-h4b64cdc_5.tar.bz2
and `Library/bin/curl.exe` is there, as expected.
```
$ tar xvf curl-7.71.1-h4b64cdc_5.tar.bz2 
info/files
info/hash_input.json
info/paths.json
info/index.json
info/about.json
info/git
info/test/run_test.bat
info/recipe/parent/install_dll.bat
info/recipe/parent/install_static.bat
info/recipe/parent/bld.bat
info/licenses/COPYING
info/recipe/conda_build_config.yaml
info/recipe/meta.yaml
info/recipe/parent/meta.yaml
info/recipe/parent/build.sh
Library/bin/curl.exe
```

It looks very likely that #81 has inadvertently removed `curl.exe` from `curl`, too!

**Comment by xylar** [comment]
I have been working for many hours trying to figure out why I'm getting:
```
'curl' is not recognized as an internal or external command,
operable program or batch file.
```
in builds of 
https://github.com/conda-forge/leptonica-feedstock/pull/22
and finally figured out that `curl.exe` just isn't there.

**Comment by ocefpaf** [comment]
Ouch! I wonder if we are even testing that properly. Let me try to fix it but we should send a PR to admin to remove those packages too.

**Comment by xylar** [comment]
I wondered as well why the tests passed.  My guess is that `curl.exe` is maybe being found somewhere else by accident during testing.

**Comment by ocefpaf** [comment]
It is probably in the image. In AppVeyor we had a workaround for it. I'm sending a PR to test it.

**Comment by isuruf** [comment]
@xylar, we already remove a lot of directories from PATH in https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/master/recipe/run_conda_forge_build_setup_win.bat#L28. Can you figure out the directory where curl is coming from in Azure and remove it?

**Comment by ocefpaf** [comment]
Closed in #83.

**Comment by isuruf** [comment]
Can somebody send a PR to  https://github.com/conda-forge/conda-forge-ci-setup-feedstock to remove curl from `PATH`? (Or create an issue?)

**Comment by jakirkham** [comment]
Historically we have used `curl` to bootstrap CI with enough things to get started as it is on all platforms. So if we do opt to remove it on Windows, it would be good to double check we are not using it anywhere for this purpose still.
